SportStore/SportsStore/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using SportsStore.Models;
using SportsStore.Models.ViewModels;

namespace SportsStore.Controllers
{
    public class ProductController : Controller
    {
        #region Fields
        private IProductRepository _repository;
        public int PageSize = 4;
        #endregion

        #region Constructors
        public ProductController(IProductRepository repository)
        {
            _repository = repository;
        }
        #endregion

        #region Methods
        public ViewResult List(string category, int productPage = 1)
            => View(
                new ProductListViewModel
                {
                    Products = _repository.Products
                        .Where(p=>category==null||p.Category==category)
                        .OrderBy(p => p.ProductID)
                        .Skip((productPage - 1) * PageSize)
                        .Take(PageSize),
                    PagingInfo = new PagingInfo
                    {
                        CurrentPage = productPage,
                        ItemPerPage = PageSize,
                        TotalItems =category==null?
                            _repository.Products.Count():
                            _repository.Products.Where(e=>
                            e.Category==category).Count()
                    },
                    CurrentCategory=category
                });

        #endregion
    }
}

SportStore/SportsStore/Views/Shared/ProductSummary.cshtml
@model Product

<div class="card card-outline-primary m1-p1">
    <div class="bg-faded p-1">
        <h4>
            @Model.Name
            <span class="badge badge-pill badge-primary" style="float:right">
                <small>@Model.Price.ToString("c")</small>
            </span>
        </h4>
    </div>
    <form id="@Model.ProductID" asp-action="AddToCard"
          asp-controller="Cart" method="post">
        <input type="hidden" asp-for="ProductID" />
        <input type="hidden" name="returnUrl"
               value="@ViewContext.HttpContext.Request.PathAndQuary()" />
        <span class="card-text p-1">
            @Model.Description
            <button type="submit"
                    class="btn btn-success btn-sm pull-right" style="float:right">
                Add To Cart
            </button>
        </span>
    </form>
</div>

SportStore/SportsStore/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width"/>
    <link rel="stylesheet" asp-href-include="lib/bootstrap/dist/css/*min.css"/>
    <title>@ViewBag.Title</title>
    <style>
        .input-validation-error {border-color:red; background-color:#fee;}
    </style>
    <script src="~/lib/jquery/jquery.min.js"></script>
    <script src="~/lib/jquery-validate/jquery.validate.min.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
</head>
<body class="m-1 p-1">
    <div class="bg-info p-2 row">
        <div class="col">
            <h4>@ViewBag.Title</h4>
        </div>
        <div class="col-2 text-right">
            <a class="btn btn-sm btn-primary"
               asp-action="Logout" asp-controller="Account">Log Out</a>
        </div>
    </div>
    @*<div class="bg-info p-2"><h4>@ViewBag.Title</h4></div>*@
    @if (TempData["message"]!=null)
    {
        <div class="alert alert-success">@TempData["message"]</div>
    }
    @RenderBody()
</body>
</html>

SportStore/SportsStore/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link rel="stylesheet"
          asp-href-include="/lib/bootstrap/dist/**/*.min.css"
          asp-href-exclude="**/*/-rebot*, **/*/-grid*" />
    @*
        <link asp-href-include="" rel="stylesheet" />*@
    <link href="~/lib/fontawesome-iconpicker/css/fontawesome-iconpicker.min.css" rel="stylesheet" />
    <title>SportsStore</title>

    @*
        <link href="lib/twitter-bootstrap/css/bootstrap.min.css" rel="stylesheet" />*@
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" />
    <style>
        .placeholder {
            visibility: collapse;
            display: none
        }

            .placeholder:only-child {
                visibility: visible;
                display: flex;
            }
    </style>
</head>
<body>
    <div class="navbar navbar-inverse bg-dark" role="navigation">
        <div class="row">
            <a class="col-8 navbar-brand" asp-action="List"
               asp-controller="Product" asp-route-category="">
                SPORTS STORE
            </a>
        </div>
        <div class="col-4 text-right">
            @await Component.InvokeAsync("CartSummary")
        </div>
    </div>

    <div class="row m-1 p-1">
        <div id="categories" class="col-3">
            @await Component.InvokeAsync("NavigationMenu")
        </div>
        <div class="col-9">
            @RenderBody()
        </div>
    </div>


    @*
        <script src="~/lib/twitter-bootstrap/js/bootstrap.min.js"></script>*@

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>
</html>